# Generated by Django 3.2.13 on 2022-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0002_auto_20220421_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_five',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 5'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_five_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 4'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_four_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 3'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 2'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
    ]
