# Generated by Django 3.2.13 on 2022-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0004_auto_20220422_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='line_one',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_unit_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_with_tax',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_without_tax',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type_of_sales',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
